const menu = [
    {
      id: 1,
      title: 'Camel',
      category: 'History',
      time: 15,
      img: 'https://image.shutterstock.com/image-photo/camel-near-pyramids-hot-desert-600w-2028526565.jpg',
      desc: `Camel near pyramids in hot desert of Egypt.Back then its use for transportation for both movement of persons and goods `,
    },
    {
      id: 2,
      title: 'Basic Ideas',
      category: 'Science',
      time: 16,
      img: 'https://image.shutterstock.com/image-illustration/stem-education-hard-sciences-technical-600w-2094463804.jpg',
      desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
    },
    {
      id: 3,
      title: 'Maths operators',
      category: 'Mathematics',
      time: 10,
      img: 'https://image.shutterstock.com/image-photo/set-math-symbol-draw-by-600w-653523058.jpg',
      desc: `Math Operators are very importants for the understanding of Maths`,
    },
    {
      id: 4,
      title: 'Another Pharaoh Image',
      category: 'History',
      price: 20,
      img: 'https://image.shutterstock.com/image-photo/magetan-juuly-2017-statue-king-600w-775869256.jpg',
      desc: `Pharoah was a respected god among his people `,
    },
    {
      id: 5,
      title: 'Understanding Titration',
      category: 'Science',
      time: 30,
      img: 'https://image.shutterstock.com/image-photo/small-children-spend-experiments-chemical-600w-374611855.jpg',
      desc: `You can do alot with chemicals if you know more about them `,
    },
    {
      id: 6,
      title: 'Basic Shapes in Maths',
      category: 'Mathematics',
      time: 18,
      img: 'https://image.shutterstock.com/image-vector/realistic-3d-color-basic-shapes-600w-1562183542.jpg',
      desc: `Realistic 3D color basic shapes. Solid colored geometric forms, cylinder and colorful cube shape. Maths geometrical figure form, realistic shapes`,
    },
    {
      id: 7,
      title: 'Images of Pharaoh',
      category: 'History',
      time: 20,
      img:'https://image.shutterstock.com/image-photo/stone-pharaoh-tutankhamen-mask-on-600w-348421580.jpg',
      desc: `Stone pharaoh tutankhamen mask on dark background  `,
    },
    {
      id: 8,
      title: 'Scientific Methods',
      category: 'Science',
      time: 17,
      img:'https://image.shutterstock.com/image-vector/science-diagram-show-step-scientific-600w-2066502653.jpg',
      desc: ` Understand science and the methods that involves discovery`,
    },
    {
      id: 9,
      title: 'quarantine buddy',
      category: 'Mathematics',
      time: 15,
      img: 'https://image.shutterstock.com/image-vector/complex-math-calculations-chalk-green-600w-2023795919.jpg',
      desc: `Math calculations with chalk green chalkboard illustration. Trigonometric formulas with algebraic computation with geometric drawings basic equations and theorem. Vector university.`,
    },
    {
      id: 10,
      title: 'Oral English',
      category: 'English',
      time: 10,
      // img: './images/item-9.jpeg',S
      img:'https://image.shutterstock.com/image-vector/cartoon-talking-black-man-expressions-600w-1096082177.jpg',
      desc: `Oral language is the system through which we use spoken words to express knowledge, ideas, and feelings. Developing ELs' oral language, then, means developing the skills and knowledge that go into listening and speaking—all of which have a strong relationship to reading comprehension.`,
    },
    {
      id: 11,
      title: 'English Pronoun',
      category: 'English',
      time: 10,
      // img: './images/item-9.jpeg',S
      img:'https://image.shutterstock.com/image-vector/pronouns-english-language-school-banner-600w-1197515686.jpg',
      desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
    },
    {
      id: 12,
      title: 'Conjuction',
      category: 'English',
      time: 10,
      // img: './images/item-9.jpeg',S
      img:'https://image.shutterstock.com/image-vector/part-speechconjunctions-additionconjunctions-grammar-rules-600w-2168631597.jpg',
      desc: `In grammar, a conjunction is a part of speech that connects words, phrases, or clauses that are called the conjuncts of the conjunctions. That definition may overlap with that of other parts of speech and so what constitutes a "conjunction" must be defined for each language.`,
    },
    {
      id: 13,
      title: 'Part of Speech',
      category: 'English',
      time: 10,
      img:'https://image.shutterstock.com/image-vector/parts-speech-english-learning-on-600w-1778424170.jpg',
      desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
    },
  ];
  export default menu;
  